    server:
      port: 8080
      address: 0.0.0.0
      servlet:
        session:
          cookie:
            same-site: lax
      forward-headers-strategy: framework


    spring:
      servlet:
        multipart:
          max-file-size: 20MB
          max-request-size: 20MB
      security:
        filter:
          dispatcher-types: ASYNC, FORWARD, INCLUDE, ERROR, REQUEST
        oauth2:
          client:
            registration:
              kakao:
                client-id: ${KAKAO_CLIENT_ID}
                client-secret: ${KAKAO_CLIENT_SECRET}
                redirect-uri: "https://api.dongcheolcoding.life/login/oauth2/code/kakao"
                authorization-grant-type: authorization_code
                client-authentication-method: client_secret_post
                scope:
                  - profile_nickname
                  - profile_image
                  - account_email
            provider:
              kakao:
                authorization-uri: https://kauth.kakao.com/oauth/authorize
                token-uri: https://kauth.kakao.com/oauth/token
                user-info-uri: https://kapi.kakao.com/v2/user/me
                user-name-attribute: id

      datasource:
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
        driver-class-name: ${DRIVER_CLASS_NAME}
        url: ${URL}

      jwt:
        secret: ${JWT_SECRET}

      jpa:
        hibernate:
          ddl-auto: create
        show-sql: true
        properties:
          hibernate.format_sql: true

      messages:
        basename: messages
        encoding: UTF-8

      mail:
        host: smtp.naver.com
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
          mail.smtp.auth: true
          mail.smtp.starttls.enable: true
          mail.smtp.ssl.trust: smtp.naver.com


    app:
      client:
        host: ${CLIENT_HOST}
      cookie:
        root-domain: "dongcheolcoding.life"
        max-days: 14
      front:
        success-url: "https://dongcheolcoding.life/account/kakaoauth"

    cloud:
      aws:
        s3:
          bucket: ${BUCKET_NAME}
        credentials:
          access-key: ${AWS_ACCESS_KEY}
          secret-key: ${AWS_SECRET_KEY}
        region:
          static: ap-northeast-2
        stack:
          auto: false

    logging:
      level:
        org.springframework.security: DEBUG
        org.springframework.security.oauth2: DEBUG

    springdoc:
      swagger-ui:
        disable-swagger-default-url: true
        config-url: /v3/api-docs/swagger-config
        url: /v3/api-docs
        path: /swagger-ui.html
        operationsSorter: method
        display-request-duration: true

    management:
      server:
        port:
      endpoints:
        web:
          base-path: /actuator
          exposure:
            include: health
      endpoint:
        health:
          show-details: always

    kakaopay:
      api:
        cid: TC0ONETIME
        secret:
          key: ${KAKAO_SECRET_KEY}
        approval-url: https://api.dongcheolcoding.life/api/payment/approve
        cancel-url: https://api.dongcheolcoding.life/api/payment/cancel
        fail-url: https://api.dongcheolcoding.life/api/payment/fail





